/**
 * Compatibility version sheet generator (GH-079): exact Bun, TypeScript,
 * browser, and pinned htmx dialect versions from versioned source —
 * never hand-edited claims. The freshness owner note is part of the
 * contract: regenerate on every dependency or dialect change.
 */
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const REPO = join(import.meta.dir, "..", "..");

async function render(): Promise<string> {
  const root = JSON.parse(readFileSync(join(REPO, "package.json"), "utf8"));
  const dev = root.devDependencies as Record<string, string>;
  const { htmx2 } = await import("@bundar/htmx/2");
  const { htmx4Experimental } = await import("@bundar/htmx/4");
  const stable = htmx2.describeAsset();
  const beta = htmx4Experimental.describeAsset();

  const lines = [
    "# Compatibility: exact versions",
    "",
    "<sub>Generated by `bun run docs:generate` (GH-079) from versioned source (package manifests and the dialect adapters' pinned asset registry). Current as of the generating commit. Freshness owner: the maintainer merging the dependency/dialect change must regenerate and commit this file in the same change.</sub>",
    "",
    "| Component | Version | Source |",
    "| --- | --- | --- |",
    `| Bun (runtime, engines) | \`${root.engines.bun}\` (CI on \`${root.packageManager}\`) | package.json |`,
    `| TypeScript | \`${dev.typescript}\` | devDependencies |`,
    `| ESLint | \`${dev.eslint}\` | devDependencies |`,
    `| htmx 2 (stable/default) | \`${stable.version}\` — integrity \`${(stable.integrity ?? "").slice(0, 19)}…\` | pinned dialect profile |`,
    `| htmx 4 (⚠️ experimental, no GA claim) | \`${beta.version}\` — integrity \`${(beta.integrity ?? "").slice(0, 19)}…\` | pinned dialect profile |`,
    "",
    "Browser lanes run Chrome for Testing via the Playwright CLI; the exact",
    "browser build is recorded per run in `artifacts/conformance/*.json` and",
    "the gate transcripts under `delivery/gates/`.",
    "",
    "Experimental markers: every htmx 4 item above is `maturity:",
    "experimental` [provisional]. GA revalidation is mandatory (M7).",
    "",
  ];
  return lines.join("\n");
}

if (import.meta.main) {
  const target = join(REPO, "docs", "compatibility", "versions.md");
  const sheet = await render();
  const before = existsSync(target) ? readFileSync(target, "utf8") : "";
  writeFileSync(target, sheet);
  console.log(
    before === sheet
      ? "docs:generate: compatibility/versions.md up to date"
      : "docs:generate: compatibility/versions.md regenerated",
  );
}
