// GENERATED by @bundar/cli routes:generate — do not edit.
// Changes to named routes must be regenerated; CI runs routes:check.

export interface RouteUrls {
  "asset-htmx"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "health"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "home"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "subscribe"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
}

function encodeQuery(query: Record<string, string | number | readonly (string | number)[]>): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (Array.isArray(value)) {
      for (const entry of value) params.append(key, String(entry));
    } else {
      params.append(key, String(value));
    }
  }
  const text = params.toString();
  return text === "" ? "" : `?${text}`;
}

export const urls = {
  "asset-htmx": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.asset-htmx: missing required path parameter "${name}"`);
      }
    }
    const raw = "/assets/htmx.js";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "health": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.health: missing required path parameter "${name}"`);
      }
    }
    const raw = "/healthz";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "home": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.home: missing required path parameter "${name}"`);
      }
    }
    const raw = "/";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "subscribe": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.subscribe: missing required path parameter "${name}"`);
      }
    }
    const raw = "/subscribe";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
} satisfies RouteUrls;
