// GENERATED by @bundar/cli routes:generate — do not edit.
// Changes to named routes must be regenerated; CI runs routes:check.

export interface RouteUrls {
  "user-show"(params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "user-create"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "search"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
}

function encodeQuery(query: Record<string, string | number | readonly (string | number)[]>): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (Array.isArray(value)) {
      for (const entry of value) params.append(key, String(entry));
    } else {
      params.append(key, String(value));
    }
  }
  const text = params.toString();
  return text === "" ? "" : `?${text}`;
}

export const urls = {
  "user-show": (params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = ["id"];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error("urls.user-show: missing required path parameter \"" + name + "\"");
      }
    }
    const raw = "/users/:id";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "user-create": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error("urls.user-create: missing required path parameter \"" + name + "\"");
      }
    }
    const raw = "/users";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "search": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error("urls.search: missing required path parameter \"" + name + "\"");
      }
    }
    const raw = "/search";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
} satisfies RouteUrls;
