/**
 * Route manifest generation and typed URL builders (GH-073).
 *
 * `buildRouteManifest` derives a deterministic manifest from a route
 * manifest (routes + names from meta.name); `generateRoutesModule` emits a
 * typed TypeScript module of URL builders from it. The generator works only
 * on the already-registered descriptor data — it never invokes handlers or
 * executes any application code.
 */
import type { RouteDescriptor } from "./routing/types";
import type { RouteManifest } from "./module";

export interface ManifestRouteEntry {
  readonly name: string;
  readonly path: string;
  readonly params: readonly string[];
  readonly methods: readonly string[];
}

export interface RouteManifestFile {
  readonly generatedAt: string;
  readonly routes: readonly ManifestRouteEntry[];
}

/** Extracts `:param` names from a normalized route path. */
export function pathParams(path: string): readonly string[] {
  const params: string[] = [];
  for (const segment of path.split("/")) {
    if (segment.startsWith(":")) {
      const name = segment.slice(1).split(".")[0]!.split("?")[0]!;
      if (!params.includes(name)) params.push(name);
    }
  }
  return params;
}

function routeName(route: RouteDescriptor): string | null {
  const meta = route.meta as { name?: unknown } | undefined;
  if (!meta || typeof meta.name !== "string" || meta.name === "") return null;
  return meta.name;
}

/**
 * Builds the deterministic manifest. Only named routes (meta.name) are
 * included — unnamed routes cannot be referenced by typed builders.
 * Routes appear in registration order; output is stable across runs.
 */
export function buildRouteManifest(manifest: RouteManifest): RouteManifestFile {
  const routes: ManifestRouteEntry[] = [];
  const seen = new Map<string, number>();

  manifest.routes.forEach((route, index) => {
    const name = routeName(route);
    if (name === null) return;
    const duplicate = seen.get(name);
    if (duplicate !== undefined) {
      throw new Error(
        `duplicate route name "${name}": declared at positions ${duplicate + 1} and ${index + 1}; route names must be unique`,
      );
    }
    seen.set(name, index);
    routes.push(
      Object.freeze({
        name,
        path: route.path,
        params: Object.freeze(pathParams(route.path)),
        methods: Object.freeze([...route.methods]),
      }),
    );
  });

  return Object.freeze({
    // Fixed epoch timestamp: output depends only on routes, never wall clock.
    generatedAt: "1970-01-01T00:00:00.000Z",
    routes: Object.freeze(routes),
  });
}

function tsTypeForParams(params: readonly string[]): string {
  if (params.length === 0) return "Record<never, never>";
  return `{ ${params.map((p) => `${p}: string | number`).join("; ")} }`;
}

function encodePath(
  path: string,
  params: Record<string, string | number>,
): string {
  return path
    .split("/")
    .map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const name = segment.slice(1);
      const value = params[name];
      if (value === undefined) {
        throw new Error(`missing required path parameter "${name}"`);
      }
      return encodeURIComponent(String(value));
    })
    .join("/");
}

/**
 * Emits the typed URL-builder module source. The generated module:
 * - types each builder's params from its route path (`missing required param`
 *   is a typecheck error, plus a runtime throw);
 * - accepts an optional query object; repeated values via arrays;
 * - percent-encodes path segments and query keys/values.
 */
export function generateRoutesModule(file: RouteManifestFile): string {
  const lines: string[] = [
    "// GENERATED by @bundar/cli routes:generate — do not edit.",
    "// Changes to named routes must be regenerated; CI runs routes:check.",
    "",
    "export interface RouteUrls {",
    ...file.routes.map(
      (route) =>
        `  ${JSON.stringify(route.name)}(params: ${tsTypeForParams(route.params)}, query?: Record<string, string | number | readonly (string | number)[]>): string;`,
    ),
    "}",
    "",
    "function encodeQuery(query: Record<string, string | number | readonly (string | number)[]>): string {",
    "  const params = new URLSearchParams();",
    "  for (const [key, value] of Object.entries(query)) {",
    "    if (Array.isArray(value)) {",
    "      for (const entry of value) params.append(key, String(entry));",
    "    } else {",
    "      params.append(key, String(value));",
    "    }",
    "  }",
    "  const text = params.toString();",
    '  return text === "" ? "" : `?${text}`;',
    "}",
    "",
    "export const urls = {",
  ];

  for (const route of file.routes) {
    const paramNames = route.params.map((p) => JSON.stringify(p)).join(", ");
    lines.push(
      `  ${JSON.stringify(route.name)}: (params: ${tsTypeForParams(route.params)}${route.params.length === 0 ? " = {}" : ""}, query?: Record<string, string | number | readonly (string | number)[]>) => {`,
      `    const required: readonly string[] = [${paramNames}];`,
      `    for (const name of required) {`,
      `      if ((params as Record<string, unknown>)[name] === undefined) {`,
      `        throw new Error(\`urls.${route.name}: missing required path parameter "\${name}"\`);`,
      `      }`,
      `    }`,
      `    const raw = ${JSON.stringify(route.path)};`,
      `    const filled = raw.split("/").map((segment) => {`,
      `      if (!segment.startsWith(":")) return segment;`,
      `      const value = (params as Record<string, string | number>)[segment.slice(1)];`,
      `      return value === undefined ? segment : encodeURIComponent(String(value));`,
      `    }).join("/");`,
      `    return \`\${filled}\${query ? encodeQuery(query) : ""}\`;`,
      `  },`,
    );
  }

  lines.push("} satisfies RouteUrls;", "");
  return lines.join("\n");
}

/** Re-derives the manifest and compares byte-for-byte for stale detection. */
export function isStale(current: string, expected: string): boolean {
  return current !== expected;
}

export { encodePath };
