/**
 * Shared playwright-cli lane runner for BR-075 lanes (accessibility,
 * no-JS): same invocation contract as tests/browser/run.ts — every step's
 * stdout/stderr/command is archived, and required steps throw on nonzero.
 *
 * Wrapper resolution (BR-091): the CLI entry point is resolved in order —
 * explicit `BUNDAR_PLAYWRIGHT_CLI` override, the local Codex skill
 * wrapper when present, and otherwise a generated portable shim that
 * execs `npx --yes --package @playwright/cli playwright-cli` with the
 * same session-flag contract. The shim is what makes the lanes runnable
 * in CI (the dedicated browser job) on any machine with node + network.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { chmod } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dir, "..", "..", "..");

export interface LaneRunner {
  run(name: string, args: string[], required?: boolean): Promise<number>;
  artifactDirectory: string;
}

export type CliSource = "override" | "codex" | "generated-shim";

export function resolvePlaywrightCli(
  env: Record<string, string | undefined>,
  sharedBinDirectory: string,
): { path: string; source: CliSource } {
  const override = env["BUNDAR_PLAYWRIGHT_CLI"];
  if (override) return { path: override, source: "override" };

  const home = env.HOME ?? "/tmp";
  const codexHome = env.CODEX_HOME ?? join(home, ".codex");
  const codexWrapper = join(
    codexHome,
    "skills",
    "playwright",
    "scripts",
    "playwright_cli.sh",
  );
  if (existsSync(codexWrapper)) return { path: codexWrapper, source: "codex" };

  // Portable shim: identical session-flag contract to the Codex wrapper.
  const shimPath = join(sharedBinDirectory, "playwright_cli.sh");
  if (!existsSync(shimPath))
    return { path: shimPath, source: "generated-shim" };
  return { path: shimPath, source: "generated-shim" };
}

export const SHIM_SOURCE = `#!/usr/bin/env bash
# Generated by tests/browser/lanes/cli.ts (BR-091): portable playwright-cli
# entry with the same session-flag handling as the local skill wrapper.
set -euo pipefail

if ! command -v npx >/dev/null 2>&1; then
  echo "Error: npx is required but not found on PATH." >&2
  exit 1
fi

has_session_flag="false"
for arg in "$@"; do
  case "$arg" in
    --session|--session=*)
      has_session_flag="true"
      break
      ;;
  esac
done

cmd=(npx --yes --package @playwright/cli playwright-cli)
if [[ "\${has_session_flag}" != "true" && -n "\${PLAYWRIGHT_CLI_SESSION:-}" ]]; then
  cmd+=(--session "\${PLAYWRIGHT_CLI_SESSION}")
fi
cmd+=("$@")

exec "\${cmd[@]}"
`;

async function ensurePlaywrightCli(
  env: Record<string, string | undefined>,
  sharedBinDirectory: string,
): Promise<{ path: string; source: CliSource }> {
  const resolved = resolvePlaywrightCli(env, sharedBinDirectory);
  if (resolved.source === "generated-shim") {
    await mkdir(sharedBinDirectory, { recursive: true });
    await writeFile(join(sharedBinDirectory, "playwright_cli.sh"), SHIM_SOURCE);
    await chmod(join(sharedBinDirectory, "playwright_cli.sh"), 0o755);
  }
  return resolved;
}

export async function createLaneRunner(lane: string): Promise<LaneRunner> {
  const sharedBinDirectory = join(
    repositoryRoot,
    "output",
    "playwright",
    ".bin",
  );
  const artifactDirectory = join(repositoryRoot, "output", "playwright", lane);
  await mkdir(artifactDirectory, { recursive: true });
  const session = `bundar-${lane}`;
  const pwcli = (await ensurePlaywrightCli(process.env, sharedBinDirectory))
    .path;

  const run = async (
    name: string,
    args: string[],
    required = true,
  ): Promise<number> => {
    const command = [pwcli, `-s=${session}`, ...args];
    const processHandle = Bun.spawn(command, {
      cwd: artifactDirectory,
      env: { ...process.env, PLAYWRIGHT_CLI_SESSION: session },
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(processHandle.stdout).text(),
      new Response(processHandle.stderr).text(),
      processHandle.exited,
    ]);
    await writeFile(join(artifactDirectory, `${name}.stdout.txt`), stdout);
    await writeFile(join(artifactDirectory, `${name}.stderr.txt`), stderr);
    await writeFile(
      join(artifactDirectory, `${name}.command.txt`),
      `$ ${command.join(" ")}\n`,
    );
    if (required && exitCode !== 0)
      throw new Error(
        `${name} failed with exit ${exitCode}: ${stderr || stdout}`,
      );
    return exitCode;
  };

  return { run, artifactDirectory };
}

/**
 * Runs an in-page assertion. `body` is the source of an async function
 * (e.g. `async () => { ... }`) evaluated in the page; it must return a
 * truthy value or throw — failures surface as nonzero CLI exit with the
 * thrown message archived under `<label>.stderr.txt`.
 */
export async function assertInPage(
  runner: LaneRunner,
  label: string,
  body: string,
): Promise<void> {
  const wrapped =
    `async page => { const message = await page.evaluate(async () => { ` +
    `try { return "OK:" + String(await (${body})()); } ` +
    `catch (error) { return "FAIL:" + (error && error.message ? error.message : String(error)); } }); ` +
    `if (message.startsWith("FAIL:")) throw new Error(${JSON.stringify(label)} + ": " + message.slice(5)); ` +
    `return message.slice(3); }`;
  await runner.run(label, ["run-code", wrapped]);
}
