// GENERATED by @bundar/cli routes:generate — do not edit.
// Changes to named routes must be regenerated; CI runs routes:check.

export interface RouteUrls {
  "login"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "article-create"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "article-edit"(params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "article-delete"(params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "login-page"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "root"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "article-list"(params: Record<never, never>, query?: Record<string, string | number | readonly (string | number)[]>): string;
  "article-detail"(params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>): string;
}

function encodeQuery(query: Record<string, string | number | readonly (string | number)[]>): string {
  const params = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (Array.isArray(value)) {
      for (const entry of value) params.append(key, String(entry));
    } else {
      params.append(key, String(value));
    }
  }
  const text = params.toString();
  return text === "" ? "" : `?${text}`;
}

export const urls = {
  "login": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.login: missing required path parameter "${name}"`);
      }
    }
    const raw = "/login";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "article-create": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.article-create: missing required path parameter "${name}"`);
      }
    }
    const raw = "/articles";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "article-edit": (params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = ["id"];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.article-edit: missing required path parameter "${name}"`);
      }
    }
    const raw = "/articles/:id/edit";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "article-delete": (params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = ["id"];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.article-delete: missing required path parameter "${name}"`);
      }
    }
    const raw = "/articles/:id/delete";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "login-page": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.login-page: missing required path parameter "${name}"`);
      }
    }
    const raw = "/login";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "root": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.root: missing required path parameter "${name}"`);
      }
    }
    const raw = "/";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "article-list": (params: Record<never, never> = {}, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = [];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.article-list: missing required path parameter "${name}"`);
      }
    }
    const raw = "/articles";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
  "article-detail": (params: { id: string | number }, query?: Record<string, string | number | readonly (string | number)[]>) => {
    const required: readonly string[] = ["id"];
    for (const name of required) {
      if ((params as Record<string, unknown>)[name] === undefined) {
        throw new Error(`urls.article-detail: missing required path parameter "${name}"`);
      }
    }
    const raw = "/articles/:id";
    const filled = raw.split("/").map((segment) => {
      if (!segment.startsWith(":")) return segment;
      const value = (params as Record<string, string | number>)[segment.slice(1)];
      return value === undefined ? segment : encodeURIComponent(String(value));
    }).join("/");
    return `${filled}${query ? encodeQuery(query) : ""}`;
  },
} satisfies RouteUrls;
