/**
 * docs:site:check — fail-closed hygiene for the public docs website.
 *
 * 1. Freshness: recomputes every synced page in memory and compares with
 *    what is on disk (a stale checkout fails loudly instead of building an
 *    outdated site).
 * 2. Evidence separation: engineering-corpus references (GH-###, BR-###)
 *    are banned from the developer path; only release-notes pages may carry
 *    them (release history legitimately cites its own work items).
 * 3. Internal-link integrity: every /docs/<slug>/ link generated by the
 *    sync must resolve to a real page.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import {
  manifestItems,
  loadManifest,
  REPO_ROOT,
  SITE_CONTENT,
  transformPage,
} from "./sync-content";

const failures: string[] = [];
const EVIDENCE_MARKER = /\b(?:GH|BR)-\d{3}\b/g;

const manifest = loadManifest();
const items = manifestItems(manifest);
const bySource = new Map(items.map((item) => [item.src, item]));
const validSlugs = new Set(["index", ...items.map((item) => item.slug)]);

// ---- 1. freshness ----
for (const item of items) {
  const destination = join(SITE_CONTENT, `${item.slug}.md`);
  if (!existsSync(destination)) {
    failures.push(
      `missing page: ${item.slug}.md — run \`bun run docs:site:sync\``,
    );
    continue;
  }
  const expected = transformPage(
    item,
    readFileSync(join(REPO_ROOT, "docs", item.src), "utf8"),
    bySource,
  );
  const actual = readFileSync(destination, "utf8");
  if (actual !== expected) {
    failures.push(
      `stale page: ${item.slug}.md — source docs changed; run \`bun run docs:site:sync\``,
    );
  }
}

// ---- 2. evidence separation + 3. internal links ----
for (const item of items) {
  const destination = join(SITE_CONTENT, `${item.slug}.md`);
  if (!existsSync(destination)) continue;
  const content = readFileSync(destination, "utf8");

  if (!item.slug.startsWith("release-notes/")) {
    const markers = content.match(EVIDENCE_MARKER) ?? [];
    if (markers.length > 0) {
      failures.push(
        `evidence markers in developer path: ${item.slug}.md contains ${markers.length} GH-/BR- reference(s) (${[...new Set(markers)].join(", ")}) — engineering records stay out of the public docs path`,
      );
    }
  }

  for (const match of content.matchAll(/\]\((\/docs\/[^)#\s]+)(#[^)]*)?\)/g)) {
    const route = match[1]!;
    const slug = route.replace(/^\/docs\//, "").replace(/\/$/, "") || "index";
    if (!validSlugs.has(slug)) {
      failures.push(`broken internal link in ${item.slug}.md: ${route}`);
    }
  }
}

if (failures.length > 0) {
  console.error(`docs:site:check FAILED (${failures.length}):`);
  for (const failure of failures) console.error(`  - ${failure}`);
  process.exit(1);
}
console.log(
  `docs:site:check: ok (${items.length} pages fresh, evidence-separated, internal links resolve)`,
);
